"""KRX 일별 섀도 피처 덤프 — 연구 캐시만.

승격 금지: 이 출력만으로 메인·flat 슬리브 채택/Book A 문구 금지
(.cursor/rules/quant-thin-sample.mdc). INS·2024+ 단독 게이트 통과 전엔 관심 섀도.

  python scripts/dump_krx_shadow.py --dry
  python scripts/dump_krx_shadow.py          # KRX_USER/PASS 필요
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.datasources.krx_client import bld_for, connect, cache_put, ymd
from src.logging_setup import setup_logging, get_logger

log = get_logger("dump_krx_shadow")

OUT_DIR = (Path(__file__).resolve().parent.parent
           / "research" / "quant_review" / "data")
PROMO_BAN = (
    "PROMOTION_FORBIDDEN: KRX shadow features must not promote main/sleeve. "
    "Cash + shadow only until thin-sample gates pass."
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry", action="store_true")
    args = ap.parse_args()
    setup_logging("INFO")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    day = ymd()
    payload = {
        "asof": datetime.now(timezone.utc).isoformat(),
        "date": day,
        "note": PROMO_BAN,
        "slots": {},
    }
    if args.dry:
        payload["slots"] = {
            "fundamental_sample": {"005930": {"PER": 12.0, "PBR": 1.1}},
            "source": "dry",
        }
    else:
        client = connect()
        if client is None:
            log.warning("KRX 로그인 불가 — 빈 섀도 파일만 기록")
        else:
            bld = bld_for("fundamental_all") or "dbms/MDC/STAT/standard/MDCSTAT03501"
            rows = client.get_rows(
                bld, searchType="1", mktId="STK", trdDd=day, share="1",
            )
            sample = {}
            for r in rows[:50]:
                sym = str(r.get("ISU_SRT_CD") or "")[-6:]
                if not sym:
                    continue
                sample[sym] = {
                    "PER": r.get("PER") or r.get("WT_PER"),
                    "PBR": r.get("PBR") or r.get("WT_STKPRC_NETASST_RTO"),
                    "DIV": r.get("DIV_YD") or r.get("DVD_YLD"),
                }
            payload["slots"]["fundamental_sample"] = sample
            payload["slots"]["n_rows"] = len(rows)
            cache_put("quant_shadow_fundamental", day, sample)
    out = OUT_DIR / f"krx_shadow_{day}.json"
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    # 고정 포인터
    latest = OUT_DIR / "krx_shadow_latest.json"
    latest.write_text(out.read_text(encoding="utf-8"), encoding="utf-8")
    readme = OUT_DIR / "README_KRX_SHADOW.md"
    if not readme.exists():
        readme.write_text(
            "# KRX shadow cache\n\n"
            + PROMO_BAN + "\n\n"
            "Generated by `scripts/dump_krx_shadow.py`. "
            "Main DN12/20 stays on Toss 1m.\n",
            encoding="utf-8",
        )
    log.info("wrote %s (%s)", out, PROMO_BAN[:40])
    return 0


if __name__ == "__main__":
    sys.exit(main())
